### ISSUE TITLE
bug - url wrong

### ISSUE THREAD

**Issue by netojocelino** [kaiofelipejs/kaiofelipejs.dev#6]
the link of the project _Remote HeartCount_ was wrong, the link opens the Vanessa Mattos website.

**Comment by kaiofelipejs** [comment]
Thanks for reporting this! 
Really is a bug, the fix is deployed now. 

FYI, this repo yet not in production. The site in kaiofelipejs.dev is my [personal site.](https://github.com/kaiofelipejs/personal-site). Here I'm building a new site with a blog using gatsby :)
